name: Building frontend docker image and push to azure container registry

on:
  push:
    branches:
      - master
      paths:
        - 'frontend/**'

  pull_request:
    branches:
      - master
      paths:
        - 'frontend/**'

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Login to azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/deploytest/frontend
        working-directory: ./frontend
      - name: Push docker image to container registry
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/deploytest/frontend
        working-directory: ./frontend